onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - sharp
overrides:
  defu@<=6.1.4: '>=6.1.5'
  h3@<1.15.6: '>=1.15.6'
  h3@<1.15.9: '>=1.15.9'
  h3@<=1.15.8: '>=1.15.9'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  smol-toml@<1.6.1: '>=1.6.1'
