name: validate readme
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.9.9'
      - name: run script
        id: script
        run: |
          python readme_util.py
          echo "::set-output name=bad-values::TEST"
      - name: check variable
        run: echo "${{ steps.script.bad-values }}"
      - name: check output
        if: ${{ steps.script.bad-values != 0 }}
        uses: actions/github-script@v3
        with:
          script:
            core.setFailed(${{ steps.script.bad-values }})
