name: create tagged prerelease

on:
  push:
    branches:
      - uv

env:
  api_url: https://test.pypi.org/pypi/ao3downloader/json
  current_version: ''
  current_version_prefix: ''
  current_version_number: ''
  new_version_prefix: ''
  new_version_number: ''
  new_version: ''
  tag_name: ''

jobs:
  bump:
    name: bump version
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.set_version.outputs.new_version }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get current version
        run: |
          response=$(curl -s -w "status:%{http_code}" "${{ env.api_url }}")
          body=$(echo "$response" | sed -e 's/status\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*status://')
          if [ "$status" -eq 200 ]; then
            version=$(echo "$body" | jq -r '.info.version')
            echo "current_version=$version" >> $GITHUB_ENV
          elif [ "$status" -eq 404 ]; then
            version="0.0.0"
            echo "current_version=$version" >> $GITHUB_ENV
          else
            echo "Failed to fetch current version from ${{ env.api_url }} with status $status"
            exit 1
          fi

      - name: get current version variables
        run: |
          if [[ "${{ env.current_version }}" =~ ^([0-9]{1,4})\.([0-9]{1,2})\.([0-9]+) ]]; then
            echo "current_version_prefix=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}" >> $GITHUB_ENV
            echo "current_version_number=${BASH_REMATCH[3]}" >> $GITHUB_ENV
          fi

      - name: get new version prefix from today's date
        run: |
          today=$(date -u +%Y.%-m)
          echo $today
          echo "new_version_prefix=$today" >> $GITHUB_ENV

      - name: calculate new version number
        run: |
          if [[ "${{ env.current_version_prefix }}" == "${{ env.new_version_prefix }}" ]]; then
            new_number=$(( ${current_version_number} + 1 ))
            echo "new_version_number=$new_number" >> $GITHUB_ENV
          else
            new_number=0
            echo "new_version_number=$new_number" >> $GITHUB_ENV
          fi

      - name: calculate new version
        run: |
          new_version="${{ env.new_version_prefix }}.${{ env.new_version_number }}"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: increment version number if it is identical to the uv version
        run: |
          uv_version=$(uv version --short)
          if [[ "${{ env.new_version }}" == "$uv_version" ]]; then
            echo "new_version_number=$(( ${{ env.new_version_number }} + 1 ))" >> $GITHUB_ENV
          fi

      - name: recalculate new version
        id: set_version
        run: |
          new_version="${{ env.new_version_prefix }}.${{ env.new_version_number }}"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          
      - name: set version with uv
        run: uv version ${{ env.new_version }}

      - name: commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Bump version to ${{ env.new_version }}"

      - name: push commit
        run: |
          git push origin HEAD:${{ github.ref_name }}

  tag:
    name: tag
    needs: bump
    runs-on: ubuntu-latest
    
    outputs:
      tag_name: ${{ steps.set_tag.outputs.tag_name }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: set tag name
        id: set_tag
        run: echo "tag_name=prerelease-${{ needs.bump.outputs.new_version }}" >> $GITHUB_OUTPUT

      - name: create tag
        run: git tag "${{ steps.set_tag.outputs.tag_name }}"

      - name: push tag
        run: |
          git push origin "${{ steps.set_tag.outputs.tag_name }}"

  publish:
    name: publish
    needs: tag
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.tag.outputs.tag_name }}

      - name: setup
        uses: astral-sh/setup-uv@v5

      - name: build
        run: uv build

      - name: publish
        run: uv publish --index testpypi
