name: test publish

on:
  push:
    branches:
      - uv

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: run script
        run: bash publish.sh "prerelease-" "Test" "${{ github.ref_name }}" "true"
